/* Code generated by RoboBlockly v1.3 */
#include <linkbot.h>
CLinkbotI robot;
double radius = 1.75;
double trackwidth = 3.69;
int count;

int turns;
printf("Enter one integer: \n");
scanf(&turns);
printf(" \n");


count = 0;
while(count < turns) {
  robot.driveDistance(10, radius);
  robot.turnRight(360/turns,    radius, trackwidth);
  count = count + 1;
    robot.setSpeed(2, radius);
}
